### ISSUE TITLE
Audio Recording is not working

### ISSUE THREAD

**Issue by mehmetbaykar** [romiroma/BroadcastWriter#4]
On iOS 16.1, iPhone 14 pro max:

- Audio inputs(app and mic) are not recording.
- On console doesn't throw any error.

 Is it something to do with output settings?

**Comment by romiroma** [comment]
Hi Mehmet!

Thank you for submitting the issue!

I do not have iPhone 14 pro max to debug the issue.
But if you have, you may want to check on your own
I may suggest, the issue about `compressionProperties` 
at **BroadcastWriter.swift:22** `AVVideoExpectedSourceFrameRateKey: 60.nsNumber`

You may try to set it to `240` and see if it works on iPhone 14 pro max

**Comment by mehmetbaykar** [comment]
I can replicate the issue on iPhone 12, iPhone 13, iPhone 13 pro, iPhone 13 mini, iPhone SE(2nd Generation) and iPhone 12 Pro. I believe it is about the iOS 16 change not device issue.

**Comment by romiroma** [comment]
i have an iPhone 12 Pro, so I can try to reproduce. So in your case you do not have a video in result, only audio, right?

**Comment by mehmetbaykar** [comment]
Sorry for the typo. Only the audio is not working(no mic nor app audio), video is working fine :)

**Comment by romiroma** [comment]
Okay, I'll try to check and fix in next few days

**Comment by mehmetbaykar** [comment]
I have a similar codebase as BroadcastWriter and in my case, the audio of the mic(strangely the audio of the app works fine) stops after 7:40 minutes.  Only happens in iOS 16 or higher. I don't see any issues on previous versions(15,14 and 13)

Do you have any suggestions on what might cause the issue?

**Comment by romiroma** [comment]
So do I understand you right? 
The issue is not about this repo? 
Can you reproduce it on the Example project from this repo?

**Comment by mehmetbaykar** [comment]
The same issue is happening in this repo as well. The problem is simply the audio of the mic is not working with iOS 16 on the devices I mentioned above.

**Comment by mehmetbaykar** [comment]
Hi @romiroma ,
I have fixed the issue by adding and setting active the audio session configuration before starting to process AVAssetriter.

**Comment by noho501** [comment]
Hi @mehmetbaykar,

Can you please share sample code?  I have the same problem and still not solved.
